### ISSUE TITLE
Some Threads of Fate automation borked

### ISSUE THREAD

**Issue by KrakenLatte** [Saaappi/HelpMePlay#19]
Auto-select for Covenant during Threads of Fate is not working. Additionally, Threads of Fate is still available to level 60+ (and those still in it 50-60), so I'm requesting all the automation (including turning on ToF), remain as it were during Shadowlands. They may add it back later as well.

**Comment by Saaappi** [comment]
Enabling Threads of Fate wasn't removed prior to the release of 2.0.4. (It was _technically_ removed during the development of that release, but was re-implemented prior to the official release, so that wouldn't have phased end users.)

Thus, the only problem here is the automation for selecting a Covenant is broken. I don't have access to test it for characters below 60. However, this was working prior to November 15th.

**Comment by Saaappi** [comment]
I leveled a character to 60 without touching _Shadowlands_. Upon entering Threads of Fate at level 60, and selecting my Covenant, the automation worked as intended.

My setting for Covenants:
![image](https://user-images.githubusercontent.com/36806900/204123673-7eb8259c-6777-40c0-8315-7566d0aaec31.png)

Given that I was unable to reproduce the bug, I'm going to run with there's nothing broken here.
